sudo: required
dist: trusty
language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
  - npm test --passWithNoTests

after_success:
  - chmod +x deploy.sh
  - "./deploy.sh"