sudo: required
dist: trusty
language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules
install:
  - npm install
  - npm i -g --ignore-test-scripts
  - npm run build

after_success:
  - chmod +x deploy.sh
  - "./deploy.sh"