language: node_js
node_js:
  - '8'
before_cache:
  - pip install --user awscli

before_deploy:
  - export BUCKET=aws-dev-dashboard LOCAL_DIR=public
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - awss3-deploy
    on:
      branch: master