sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "8.0"

cache:
  directories:
    - node_modules
    -
install:
  - npm install
  - npm i -g react-deploy-cli
  - npm run build

after_success:
  - chmod +x deploy.sh
  - "./deploy.sh"